remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: VittorioCodes
description: I try to learn and develop some stuff on my way. Basically a gamer with geeky interests.

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vittoriocodes
  - name: Twitter(X)
    icon: <i class="fa-brands fa-twitter"></i>
    link: https://x.com/VittorioKun

navigation:
- name: Soulslike Games Quiz
  link: ./soulsquiz
- name: Phasmophobia İnteraktif Rehber
  link: https://tybayn.github.io/phasmo-cheat-sheet-tr/

google_analytics: G-ZPSK0ZM7JE

color-scheme: dark
logo: /soulsquiz/images/solaire_pixel.gif