theme: jekyll-theme-minimal
title: VittorioCodes Main Site
description: For Soulslike games quiz, <a href="https://vittoriocodes.github.io/soulsquiz">click me</a>

navigation:
- name: Soulslike Games Quiz
  link: ./soulsquiz.html
- name: Phasmophobia İnteraktif Rehber
  link: https://tybayn.github.io/phasmo-cheat-sheet-tr/

google_analytics: G-ZPSK0ZM7JE

color-scheme: dark
logo: /soulsquiz/images/solaire_pixel.gif